version: '3.4'

services:
  ddagent:
    image: datadog/docker-dd-agent
    environment:
      - DD_APM_ENABLED=true
      - DD_BIND_HOST=0.0.0.0
      - DD_API_KEY=[Datadog API Key]
      - DD_APM_ENV=dotNet_distributed_tracing_sandbox
    ports:
      - "8126:8126"

  backservice:
    image: triptrackerbackservice
    build:
      context: .
      dockerfile: TripTracker.BackService/Dockerfile
    environment:
      - DD_TRACE_AGENT_HOSTNAME=ddagent
      - DD_TRACE_AGENT_PORT=8126
    depends_on:
      - ddagent

  ui:
    image: triptrackerui
    environment:
      - serviceUrl=http://backservice
      - DD_TRACE_AGENT_HOSTNAME=ddagent
      - DD_TRACE_AGENT_PORT=8126
    build:
      context: .
      dockerfile: TripTracker.UI/Dockerfile
    links:
      - backservice
    depends_on:
      - ddagent

  db:
    image: "microsoft/mssql-server-linux"